---
title: About Me
url: "/about"
hidemeta: true
disableShare: true
summary:
  Abiut Nikita Kaymonov. This section details what he does & everything else you
  might want to know about him.
---

Hi there! :wave: I'm Nikita.

If you landed at this page you most likely have some interest in me.  

As a kid I used to read a lot of encyclopedias to learn about everything. Later during my master's studies I took a class in statistics with R and open the whole new world of Data Science. Being able to analyse any piece of data that I'm curious about was like obtaining a God-like power. 

Learning is my hobby and I'm always learning something new. 
If you are interested in my tech skills, just go to the [Technology Stack](../services/#technology-stack) section of my Services page.
So, in case you would like to hire me, that information might prove useful for
you! :heart:

I am a very curious person and have a wide range of interests besides data science. I love to travel and discover new places, cultures and especially new foods. I am also a very active person so my perfect place to live has a forest and a lot of mountains to hike (like in Colorado or Switzerland :mountain:)\
I also have a little obsession with foxes, but you probably noticed that 🙂



### Contact Me

Want to have a chat with me? Feel free to drop a DM!

These are the platforms you can find me on:

- Email: nikita.kaymonov@gmail.com
- Linkedin: [www.linkedin.com/in/nikita-kaymonov-a853031b9/][linkedin]
- Instagram: [@Nikita26][instagram]


<!-- Reference Links -->

[linkedin]: https://www.linkedin.com/in/nikita-kaymonov-a853031b9/
[email]: mailto:nikita.kaymonov@gmail.com
[instagram]: https://www.instagram.com/nikita26/
